title: Gábor IVÁN
subtitle: Iván is my family name
lang: en
locale: en_US
author: 'Gábor Iván'
author_slug: 'gabor.ivan'
author_avatar: 'avatar.jpg'
author_introduction: 'Hi, my name is Gábor Iván. I am a PHP developer at <a href="https://www.westwing.com" target="_blank">Westwing</a>, but I also like to deal with the Frontend part too. Of course, in a non-professional way.'

application: "Gábor Iván's intrudoction page"
timezone: 'Europe/Berlin'

description: ''
subject: ''
keywords: ''

homepage: 'https://gaborivan.de'

source: src
destination: docs

facebook_appid: 2178081495757871
facebook_username: ivan.gabor.80
twitter_username: gaborivan1980
github_username: Gixx
linkedin_username: gaborivan

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - .jekyll-cache
  - .sass-cache
  - .idea
  - node_modules

env: production


jekyll_tidy:
  exclude: ['robots.txt']
  compress_html: false

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-feed
  - jekyll-include-cache
  - uglifier
  - jekyll-last-modified-at
  - jekyll-plantuml
  - jekyll-tidy
  - classifier-reborn
  - jekyll-tagging-related_posts
  - jekyll-paginate-v2
